# Google Cloud Build Configuration
# This file tells Google Cloud Build how to build and deploy your Docker container

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/react-explorers-app:$COMMIT_SHA', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/react-explorers-app:$COMMIT_SHA']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'run'
      - 'deploy'
      - 'react-explorers-app'
      - '--image=gcr.io/$PROJECT_ID/react-explorers-app:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'

# The built image will be stored in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/react-explorers-app:$COMMIT_SHA'

# Options for the build
options:
  # Use higher CPU machines for faster builds
  machineType: 'E2_HIGHCPU_8'
  # Build timeout (adjust if needed)
  timeout: '1200s' 