steps:
  # Step 1: Try to pull the existing image for build cache (optional)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker pull us-central1-docker.pkg.dev/$PROJECT_ID/${REPO_NAME}/${BRANCH_NAME}:latest || exit 0

  # Step 2: Build the Docker image with cache + secrets
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build \
          --cache-from=us-central1-docker.pkg.dev/$PROJECT_ID/${REPO_NAME}/${BRANCH_NAME}:latest \
          -t us-central1-docker.pkg.dev/$PROJECT_ID/${REPO_NAME}/${BRANCH_NAME}:latest \
          .

  # Step 3: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/${REPO_NAME}/${BRANCH_NAME}:latest



# Optional: extend timeout if builds are large
timeout: 700s
