name: hyperspy-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - fastapi
  - uvicorn
  - hyperspy
  - python-multipart
  - numpy
  - scikit-image=0.19.3
  - scipy
  - matplotlib
  - pandas
  - pip
  - pip:
    - sparse  # Required for reading EDS spectrum data from Velox EMD files
    - hyperspy-extensions-list  # Provides additional signal types
    - hyperspy-gui-traitsui # hyperspy-extensions-list may be expired 
    - hyperspy-gui-ipywidgets  # Optional: for interactive features
  - pip:
    - hyperspy-base # no matching distribution found?